spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    logging:
      level:
        org.springframework.security: DEBUG
        org.springframework.security.web.access: DEBUG

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
