spring:
  application:
    name: app
  profiles:
    active: dev
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR

app:
  default-status: draft
