spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
