name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.3"

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Write RSA keys to files
        run: |
          mkdir -p src/test/resources/certs
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > src/test/resources/certs/private.pem
          echo "${{ secrets.RSA_PUBLIC_KEY }}" > src/test/resources/certs/public.pem


      - name: Check code style
        run: ./gradlew checkstyleMain checkstyleTest


      - name: Build project
        run: ./gradlew clean build


      - name: Run tests
        run: ./gradlew test
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: password


      - name: Jacoco report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: build/reports/jacoco/test

      - name: Run SonarCloud analysis
        run: ./gradlew sonar --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: hexlet-s7
          SENTRY_PROJECT: java-project-99
        with:
          environment: production
