name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Write RSA keys to files
        run: |
          mkdir -p src/test/resources/certs
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > src/test/resources/certs/private.pem
          echo "${{ secrets.RSA_PUBLIC_KEY }}" > src/test/resources/certs/public.pem

      - name: Build and run tests with JaCoCo
        run: ./gradlew clean build jacocoTestReport --no-daemon
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: password

      - name: Run SonarCloud analysis
        run: ./gradlew sonar --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
